form:
  url: https://docs.google.com/forms/d/e/===========================/viewform


answers:
- match:
    entry: '155208993'
    title_contains: เพศ
  type: choice
  quota:
    ชาย: 50
    หญิง: 50
- match:
    entry: '1541610141'
    title_contains: ภาควิชา
  type: choice
  quota:
    ภาควิชาเคมี: 10
    ภาควิชาคณิตศาสตร์: 10
    ภาควิชาฟิสิกส์: 10
    ภาควิชาชีววิทยา: 10
    ภาควิชาวิทยาการคอมพิวเตอร์: 10
    ภาควิชาสถิติ: 40
    ศูนย์วิเคราะห์ข้อมูลดิจิทัลอัจฉริยะพระจอมเกล้าลาดกระบัง (K-DAI): 10
- match:
    entry: '2021734169'
    title_contains: ชั้นปี
  type: choice
  quota:
    ปี 1: 20
    ปี 2: 20
    ปี 3: 25
    ปี 4: 35
- match:
    entry: '2044211618'
    title_contains: คุณเคยใช้บริการเรียกรถผ่านแอปพลิเคชั่นทั่วไปหรือไม่
  type: choice
  quota:
    เคยใช้บริการ และยังใช้อยู่: 70
    เคยใช้ แต่ไม่ใช้แล้ว (3 เดือนที่ผ่านมา): 15
    ไม่เคยใช้บริการ: 15
- match:
    entry: '1759639025'
    title_contains: รายได้เฉลี่ยต่อเดือนของคุณ
  type: choice
  quota:
    ต่ำกว่า 15,000 บาท: 70
    15,001 – 30,000 บาท: 20
    30,001 – 50,000 บาท: 10
    มากกว่า 50,000 บาท: 0
- match:
    entry: '1943820034'
    title_contains: ปกติเดินทางด้วยวิธีใด
  type: checkbox
  choices:
  - เดิน
  - รถส่วนตัว
  - วินมอเตอร์ไซต์
  - รถประจำทาง
  - รถไฟฟ้า
  - แท็กซี่
  - บริการเรียกรถรับจ้างผ่านแอป
  presence_quota:
    เดิน: 20
    รถส่วนตัว: 30
    วินมอเตอร์ไซต์: 20
    รถประจำทาง: 20
    รถไฟฟ้า: 10
    แท็กซี่: 10
    บริการเรียกรถรับจ้างผ่านแอป: 50
  min_k: 1
  max_k: 3
- match:
    entry: '2039957595'
    title_contains: ใน 3 เดือน คุณใช้บริการเรียกรถผ่านแอปพลิเคชั่นบ่อยแค่ไหน
  type: choice
  quota:
    5-7 ครั้ง / สัปดาห์: 15
    3-4 ครั้ง / สัปดาห์: 25
    1-2ครั้ง / สัปดาห์: 35
    เดือนละ 2-3 ครั้ง: 15
    เดือนละ 1 ครั้ง: 10
- match:
    entry: '73150373'
    title_contains: ประเภทบริการพาหนะใดที่เลือกใช้บ่อย
  type: choice
  quota:
    มอเตอร์ไซต์: 55
    รถยนต์: 40
    รถตู้: 5
- match:
    entry: '1859750130'
    title_contains: คุณเรียกบริการเรียกรถผ่านแอปพลิเคชั่นในพื้นที่ใด
  type: choice
  quota:
    เขตกลางเมืองกรุงเทพฯ (สามย่าน , สาทร, สีลม, อโศก): 10
    เขตชานเมืองกรุงเทพฯ: 80
    ปริมณฑล (นนทบุรี, สมุทรปราการ, ปทุมธานี ฯลฯ): 10
- match:
    entry: '888673022'
    title_contains: ปกติคุณใช้บริการเรียกรถผ่านแอปพลิเคชั่นเพื่อจุดประสงค์ใด
  type: checkbox
  choices:
  - ไปทำงาน/ไปเรียน
  - กลับบ้าน/ที่พัก
  - เดินทางไปทำธุระ
  - เดินทางท่องเที่ยว/พักผ่อน
  - ไปพบเพื่อน/ครอบครัว
  - เดินทางต่อจากรถไฟฟ้า/ขนส่งสาธารณะ
  presence_quota:
    ไปทำงาน/ไปเรียน: 30
    กลับบ้าน/ที่พัก: 35
    เดินทางไปทำธุระ: 25
    เดินทางท่องเที่ยว/พักผ่อน: 15
    ไปพบเพื่อน/ครอบครัว: 5
    เดินทางต่อจากรถไฟฟ้า/ขนส่งสาธารณะ: 10
  min_k: 1
  max_k: 3
- match:
    entry: '2106742600'
    title_contains: ในสถานการณ์ใดคุณเลือกใช้บริการ
  type: checkbox
  choices:
  - ฝนตก / อากาศไม่ดี
  - ชั่วโมงที่ไม่มีการขนส่งสาธารณะ
  - ชั่วโมงเร่งด่วน
  - เมื่อดื่มเครื่องดื่มแอลกอฮอล์
  - เมื่อไม่มีที่จอดรถ
  presence_quota:
    ฝนตก / อากาศไม่ดี: 40
    ชั่วโมงที่ไม่มีการขนส่งสาธารณะ: 30
    ชั่วโมงเร่งด่วน: 40
    เมื่อดื่มเครื่องดื่มแอลกอฮอล์: 15
    เมื่อไม่มีที่จอดรถ: 15
  min_k: 1
  max_k: 3
- match:
    entry: '1564759848'
    title_contains: ช่วงเวลาใดมากที่สุด
  type: checkbox
  choices:
  - ช่วงเช้า (05.00–09.00)
  - ช่วงกลางวัน (09.01–16.00)
  - ช่วงเย็น - ค่ำ (16.01–21.00)
  - ช่วงดึก - เช้ามืด (21.01–04.59)
  presence_quota:
    ช่วงเช้า (05.00–09.00): 10
    ช่วงกลางวัน (09.01–16.00): 30
    ช่วงเย็น - ค่ำ (16.01–21.00): 45
    ช่วงดึก - เช้ามืด (21.01–04.59): 15
  min_k: 1
  max_k: 2
- match:
    entry: '1161672675'
    title_contains: ค่าใช้จ่ายในการใช้บริการเรียกรถ
  type: choice
  quota:
    ต่ำกว่า 50 บาท: 30
    51 - 100 บาท: 40
    101 - 150 บาท: 20
    151 - 200 บาท: 10
    201 - 300 บาท: 5
    301 - 500 บาท: 1
    มากกว่า 500 บาท: 0
- match:
    entry: '693341393'
    title_contains: แอปพลิเคชั่นบริการเรียกรถที่คุณเลือกใช้เป็นประจำ
  type: choice
  quota:
    Grab: 60
    Bolt: 25
    LINE MAN: 15
    IN Drive: 0
    Taxi OK: 0
    Robinhood: 0
- match:
    entry: '545814328'
    title_contains: คุณรู้จักแอปพลิเคชั่นให้บริการเรียกรถจากช่องทางใด
  type: choice
  quota:
    โฆษณาตามพื้นที่สาธารณะ (ป้ายบิลบอร์ด): 10
    โฆษณาบนสื่อโซเชียลมีเดีย (Facebook/Tiktok/...): 30
    อินฟลูเอนเซอร์ (ผ่านโซเชียลต่างๆ): 10
    Search engine (เครื่องมือการค้นหา เช่น google ): 10
    การแนะนำแบบปากต่อปาก: 40
- match: { entry: "1258734699", title_contains: "ปัจจัยที่คุณพิจารณามากที่สุด" }
  type: choice
  quota:
    "ความสะดวกในการเรียกใช้": 25
    "ความปลอดภัย": 20
    "ความรวดเร็ว": 15
    "คุณภาพของการบริการ": 10
    "ราคา": 20
    "โปรโมชั่น/ส่วนลด": 20    
# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (คุณภาพ/ความปลอดภัย/ติดตามตำแหน่ง)
- type: multiple_choice_grid
  match:
    question_contains: "คุณภาพของรถที่คุณเรียกใช้บริการ"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "คุณภาพของรถที่คุณเรียกใช้บริการ"
    - "ความปลอดภัยตลอดการเดินทาง"
    - "ระบบติดตามตำแหน่งมีความแม่นยำ"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (ราคา/โปร่งใส)
- type: multiple_choice_grid
  match:
    question_contains: "ราคาสอดคล้องกับระยะทางที่ใช้บริการ"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "ราคาสอดคล้องกับระยะทางที่ใช้บริการ"
    - "การคิดราคามีความโปร่งใสและตรวจสอบได้"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (โปรโมชัน)
- type: multiple_choice_grid
  match:
    question_contains: "โปรโมชั่น/ส่วนลดที่ได้รับมีความน่าสนใจ"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "โปรโมชั่น/ส่วนลดที่ได้รับมีความน่าสนใจ"
    - "โปรโมชั่นมีความสม่ำเสมอและตรงกับความต้องการ"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (ความครอบคลุม/เข้าถึง)
- type: multiple_choice_grid
  match:
    question_contains: "มีการบริการครอบคลุมพื้นที่"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "มีการบริการครอบคลุมพื้นที่"
    - "สามารถเข้าถึงบริการได้ตลอดเวลาที่ต้องการ"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (คนขับ)
- type: multiple_choice_grid
  match:
    question_contains: "พนักงานขับมีความรู้และทักษะในการขับขี่ที่ปลอดภัย"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "พนักงานขับมีความรู้และทักษะในการขับขี่ที่ปลอดภัย"
    - "พนักงานขับมีมารยาทและการบริการที่ดี"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (กระบวนการ/ซัพพอร์ต)
- type: multiple_choice_grid
  match:
    question_contains: "แอปพลิเคชันใช้งานง่าย สะดวกในการเรียกรถ"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "แอปพลิเคชันใช้งานง่าย สะดวกในการเรียกรถ"
    - "การช่วยเหลือ/แก้ไขปัญหาของทีมงานฝ่ายบริการลูกค้า"
    - "ขั้นตอนการจอง/เรียกรถมีความรวดเร็ว"
    - "ระบบยืนยันการเดินทางและการชำระเงินมีความปลอดภัย"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ปัจจัยที่ส่งผลต่อการเลือกใช้บริการ (ภาพลักษณ์/สภาพแวดล้อม)
- type: multiple_choice_grid
  match:
    question_contains: "แอปพลิเคชันมีหน้าตาและการออกแบบที่น่าสนใจ"
  columns: ["ไม่เห็นด้วยอย่างยิ่ง","ไม่เห็นด้วย","ปานกลาง","เห็นด้วย","เห็นด้วยอย่างยิ่ง"]
  require_each_row: true
  rows:
    - "แอปพลิเคชันมีหน้าตาและการออกแบบที่น่าสนใจ"
    - "รถและสภาพแวดล้อมในการเดินทางสะอาดเรียบร้อย"
    - "โลโก้/แบรนด์สร้างความเชื่อมั่นและน่าไว้วางใจ"
  default_weights: {"ไม่เห็นด้วยอย่างยิ่ง":0.05,"ไม่เห็นด้วย":0.10,"ปานกลาง":0.25,"เห็นด้วย":0.35,"เห็นด้วยอย่างยิ่ง":0.25}

# --- ประสบการณ์ในการใช้บริการในแต่ละแอปฯ
- type: multiple_choice_grid
  match:
    question_contains: "ประสบการณ์ในการใช้บริการในแต่ละแอปฯ"
  columns: ["ไม่เคยใช้งาน","ไม่พอใจอย่างยิ่ง","ไม่พอใจ","ปานกลาง","พอใจ","พอใจอย่างยิ่ง"]
  require_each_row: true
  rows: ["Grab","Bolt","LINE MAN Taxi","IN Drive","Taxi OK","Robinhood"]
  default_weights: {"ไม่เคยใช้งาน":0.05,"ไม่พอใจอย่างยิ่ง":0.05,"ไม่พอใจ":0.10,"ปานกลาง":0.25,"พอใจ":0.30,"พอใจอย่างยิ่ง":0.25}

# --- ความพึงพอใจต่อแอปพลิเคชันบริการเรียกรถที่คุณใช้เป็นประจำ
- type: multiple_choice_grid
  match:
    question_contains: "ความพึงพอใจต่อแอปพลิเคชันบริการเรียกรถที่คุณใช้เป็นประจำ"
  columns: ["น้อยที่สุด","น้อย","ปานกลาง","มาก","มากที่สุด"]
  require_each_row: true
  rows:
    - "การเรียกรถผ่านแอปพลิเคชันมีความสะดวก"
    - "เวลารอรถเหมาะสม"
    - "การจับคู่คนขับรวดเร็ว"
    - "การเดินทางใช้เวลาตามที่คาดหวัง"
    - "รู้สึกปลอดภัยตลอดการเดินทาง"
    - "ฟังก์ชันแชร์ตำแหน่ง"
    - "ระบบประเมิน/รีวิวช่วยสร้างความปลอดภัย"
    - "พนักงานขับมีมารยาทและสุภาพ"
    - "พนักงานขับขี่ปลอดภัย"
    - "พนักงานขับเชี่ยวชาญเส้นทาง"
    - "แอปทำงานเสถียร ไม่ค้างหรือหลุด"
    - "ข้อมูลการเดินทาง/ค่าใช้จ่ายแสดงผลถูกต้อง"
    - "แอปพลิเคชันใช้งานง่าย สะดวกในการเรียกรถ"
    - "ราคาที่คิดตรงตามที่คาดหวัง"
    - "การคิดราคามีความโปร่งใสและตรวจสอบได้"
    - "โปรโมชั่นตรงกับความต้องการ"
    - "ความถี่ของโปรโมชั่นเหมาะสม"
    - "การออกแบบแอปพลิเคชันสวยงาม น่าเชื่อถือ"
    - "ระบบแอปพลิเคชันมีความเสถียร"
  default_weights: {"น้อยที่สุด":0.05,"น้อย":0.10,"ปานกลาง":0.25,"มาก":0.35,"มากที่สุด":0.25}
